{% extends "layouts/master.phtml" %}

{% block content %}
    <div class="container" id="app">
        <div class="uno-logo"></div>

        <div class="uno-content">
            <div class="logo"></div>
            <h1>UNO FRAMEWORK</h1>
            <p>Fork Uno framework on <a href="">Github <i class="fa fa-github-square"></i></a></p>
        </div>

        <div class="navigation">
            <ul>
                <li><a href="">About</a></li>
                <li><a href="">Documentation</a></li>
                <li><a href="">Content</a></li>
                <li><a href="">Contributors</a></li>
            </ul>
        </div>

        <div class="twelve columns about">
            <p>Built with <i class="fa fa-heart"></i> Uno PHP </p>
        </div>

    </div>

{% endblock %}